config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :rooms, only: [:show, :index, :new, :create] do
    resources :bookings, only: [:create, :new, :show, :edit, :update]
  end
  # Defines the root path route ("/")
  resources :bookings, only: [:destroy, :index]

  namespace :hospital do
    resources :bookings, only: [:index, :update]
    resources :rooms, only: [:index, :edit, :update, :destroy]
    # equivalent to => get '/<namespace>/bookings', to: '<namespace>/bookings#index'
  end

  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user

  alias_attribute :start_time, :date

  enum :status, [ :pending, :confirmed, :rejected ]
  validates :hours, presence: true, numericality: { greater_than_or_equal_to: 1 }

  def pending?
    status == 'pending'
  end
end

app/models/room.rb
class Room < ApplicationRecord
  include PgSearch::Model
  CATEGORIES = [
    "General Surgery",
    "Orthopedic Surgery",
    "Neurosurgery",
    "Cardiothoracic Surgery",
    "Gynecological Surgery",
    "Urological Surgery",
    "Ophthalmic Surgery",
    "ENT (Ear, Nose, and Throat) Surgery",
    "Plastic and Reconstructive Surgery",
    "Pediatric Surgery"
  ]

  EQUIPMENTS = [
    "Operating Table",
    "Surgical Lights",
    "Anesthesia Machine",
    "Electrocautery Device",
    "Surgical Instruments",
    "Surgical Microscope",
    "Laparoscopic Equipment",
    "Patient Monitoring System",
    "Surgical Drapes",
    "Suction System"
  ]
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many_attached :photos
  validates :name, presence: true, uniqueness: { scope: :facility_name }
  validates :facility_name, presence: true
  validates :address, presence: true
  validates :price_per_hour, presence: true
  validates :capacity, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  multisearchable against: [:address, :category, :equipment]
  pg_search_scope :address_search, against: [:address, :category, :equipment],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings # bookings as a client
  has_many :rooms
  has_many :bookings_as_hospital, through: :rooms, source: :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  include Pundit::Authorization
  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    if params[:tab] == "pending"
      @bookings = policy_scope(Booking.where(status: "pending"))
    else
      @bookings = policy_scope(Booking.where(status: "confirmed"))
    end
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @room = Room.find(params[:room_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @room = Room.find(params[:room_id])
    @booking = Booking.new(booking_params)
    @booking.room = @room
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to bookings_path(tab: "pending", room: @room)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    authorize @booking
    redirect_to bookings_path, status: :see_other, notice: 'booking was successfully deleted.'
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :date, :hours, :from, :comment).merge(user: current_user)
  end
end

app/controllers/hospital/bookings_controller.rb
class Hospital::BookingsController < ApplicationController

  def index
    @bookings = policy_scope([:hospital, Booking])
    @upcomming = @bookings.where(status: "confirmed")
    @requests = @bookings.where(status: "pending")
    # @rooms = policy_scope([:hospital, Room]) --> what if i want to policy both?
    # @rooms = Room.where(user: user)
  end

  def update
    @booking = Booking.find(params[:id])
    authorize [:hospital, @booking]
    if @booking.update(booking_params)
      redirect_to hospital_bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def booking_params
    params.require(:booking).permit(:status, :date, :hours, :from, :comment).merge(user: current_user)
  end
end

app/controllers/hospital/rooms_controller.rb
class Hospital::RoomsController < ApplicationController

  def index
    @rooms = policy_scope([:hospital, Room])
  end

  def edit
    @room = Room.find(params[:id])
    authorize([:hospital, @room])
  end

  def update
    @room = Room.find(params[:id])
    authorize([:hospital, @room])
    if @room.update(room_params)
      redirect_to hospital_rooms_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @room = Room.find(params[:id])
    authorize([:hospital, @room])
    @room.destroy
    redirect_to hospital_rooms_path, status: :see_other
  end

  private

  def room_params
    params.require(:room).permit(:name, :category, :equipment, :price_per_hour, :capacity)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
    @rooms = policy_scope(Room)

    if params[:query].present? || params[:category].present? || params[:equipment].present?
      # Search for rooms within a 10 km radius
      @rooms = Room.near(params[:query], 10) if params[:query].present?

      # Filter by category if selected
      @rooms = @rooms.where(category: params[:category]) if params[:category].present?

      # Filter by equipment if selected
      @rooms = @rooms.where(equipment: params[:equipment]) if params[:equipment].present?
    end
  end

  def show
    @room = Room.find(params[:id])
    @booking = Booking.new
    authorize @room
    @markers =
      [{
        lat: @room.latitude,
        lng: @room.longitude
      }]
  end

  def new
    @room = Room.new
    authorize @room
  end

  def create
    @room = Room.new(room_params)
    @room.user = current_user
    authorize @room
    if @room.save
      redirect_to hospital_rooms_path
    else
      # display the form for the user again
      render :new, status: :unprocessable_entity
    end
  end

  private

  def room_params
    params.require(:room).permit(:name, :facility_name, :address, :price_per_hour, :capacity, :category, :equipment, photos: [])
  end
end

# if params[:query].present? || params[:category].present? || params[:equipment].present?
#   @query_search = params[:query]
#   @rooms = Room.near(@query_search, 10)

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form-2.html.erb
<div class="w-full p-4 sticky top-0 border border-gray-300 rounded-md bg-slate-50" data-controller="booking-form" data-booking-form-room-price-value="<%= @room.price_per_hour %>">
  <%= simple_form_for([@room, @booking]) do |f| %>

    <%= f.input :date, html5: true %>
    <%= f.input :startFrom, label: "From:", html5: true %>

    <%= f.input :hours, input_html: {
      class: 'hour-input',
      id: 'hour-input',
      min: 1,
      data: {
        action: "change->booking-form#calculation",
      }
    } %>
    <%= f.input :comment, label: "Operation details:" %>
    <p>Total price: ¥ <span id="total-price" data-booking-form-target="totalPrice"><%= @room.price_per_hour %></span></p>
    <%= f.button :submit, class: "btn"%>
  <% end %>
</div>

app/views/bookings/_form.html.erb
<%= simple_form_for([@room, @booking]) do |f| %>
  <%= f.button :submit, class: "w-full text-center py-3 rounded bg-indigo-600 text-white hover:bg-green-dark focus:outline-none" %>
<% end %>




<script>
  // Get the hour input field and the total price element
  const hourInput = document.getElementById('hour-input');
  const totalPrice = document.getElementById('total-price');

  // Add an event listener to the hour input field
  hourInput.addEventListener('input', function() {
    // Calculate the new total price based on the input value and room price per hour
    const hours = parseInt(hourInput.value);
    const pricePerHour = parseInt('<%= @room.price_per_hour.to_i %>');
    const newTotalPrice = hours * pricePerHour;

    // Update the total price element with the new value
    totalPrice.textContent = newTotalPrice;
  });
</script>

app/views/bookings/show.html.erb
<p><%= @booking.status %></p>
<p><%= @booking.first_date %></p>
<p><%= @booking.last_date %></p>
<p><%= link_to 'back', bookings_path %></p>

app/views/hospital/bookings/index.html.erb
<!--

<div class="flex gap-2 ml-12 pt-3 justify-end pb-0">
    <%= link_to "Your Rooms", hospital_rooms_path, class: "text-slate-100 bg-blue-500 hover:text-blue-700 hover:bg-white active:bg-blue-600 font-bold py-2 px-4 mx-2" %>
    <%= link_to "List a new room", new_room_path, class: "text-slate-100 bg-blue-500 hover:text-blue-700 hover:bg-white active:bg-blue-600 font-bold py-2 px-4 mx-2" %>
</div>
-->

<div class="flex pt-0 mt-0">
  <div class="flex flex-col flex-1">

    <p class="text-2xl font-bold ml-12 mt-12 ">Upcoming Bookings</p>

  <p class="text-xl mt-12 mx-12"><%= current_user.rooms.any? ? "#{current_user.rooms.first.facility_name}" : "Welcome to your hospital's page , add your first room."%>
  <%= current_user.first_name %> <%= current_user.last_name %></p>



  <div class="flex gap-4 ml-12">
        <%= link_to "Your Rooms", hospital_rooms_path, class: "
          inline-block
          rounded
          bg-slate-500
          px-6
          pb-2
          mt-4
          pt-2.5
          text-xs
          font-medium
          uppercase
          leading-normal
          text-white
          shadow-[0_4px_9px_-4px_#3b71ca]
          transition
          duration-150
          ease-in-out
          hover:bg-primary-600
          hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
          focus:bg-primary-600
          focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
          focus:outline-none
          focus:ring-0
          active:bg-primary-700
          active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
        " %>

        <%= link_to "List a new room", new_room_path, class: "
          inline-block
          rounded
          bg-slate-500
          px-6
          pb-2
          mt-4
          pt-2.5
          text-xs
          font-medium
          uppercase
          leading-normal
          text-white
          shadow-[0_4px_9px_-4px_#3b71ca]
          transition
          duration-150
          ease-in-out
          hover:bg-primary-600
          hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
          focus:bg-primary-600
          focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
          focus:outline-none
          focus:ring-0
          active:bg-primary-700
          active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
        " %>
  </div>


<ul class="ml-8 mt-12 nav tabs-underlined" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <span class="nav-link tab-underlined active" id="bookings-tab" data-bs-toggle="tab" data-bs-target="#bookings-tab-pane" role="tab" aria-controls="bookings-tab-pane" aria-selected="true">Bookings</span>
  </li>
  <li class="nav-item" role="presentation">
    <span class="nav-link tab-underlined" id="requests-tab" data-bs-toggle="tab" data-bs-target="#requests-tab-pane" role="tab" aria-controls="requests-tab-pane" aria-selected="false">Requests</span>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade py-3 show active" id="bookings-tab-pane" role="tabpanel" aria-labelledby="bookings-tab" tabindex="0">
    <p class="text-2xl font-bold ml-12 mt-12"><%= @upcomming.any? ? "Your upcoming bookings" : "No bookings yet"%></p>

    <% @upcomming.each do |booking| %>
    <div
      class="
        block
        rounded-lg
        bg-white
        p-6
        w-96
        ml-12
        my-8
        shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)]
      ">
      <h5
        class="
          mb-2
          text-xl
          font-bold
          leading-tight
          text-neutral-800
        ">
        <%= booking.room.category %>
      </h5>
      <p class="mb-4 text-base text-neutral-600 dark:text-neutral-200">
        <p>Room: <%= booking.room.name %></p>
        <p>Date: <%= booking.date %></p>
        <p>Time: <%= booking.startFrom %></p>
        <p>Duration: <%= booking.hours %> hours</p>
        <p class="text-neutral-600">Details: <%= booking.comment %></p>

        <p><%= booking.comment %></p>
      </p>
      <button
        type="button"
        class="
          inline-block
          rounded
          bg-red-500
          px-6
          pb-2
          mt-4
          pt-2.5
          text-xs
          font-medium
          uppercase
          leading-normal
          text-white
          shadow-[0_4px_9px_-4px_#3b71ca]
          transition
          duration-150
          ease-in-out
          hover:bg-primary-600
          hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
          focus:bg-primary-600
          focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
          focus:outline-none
          focus:ring-0
          active:bg-primary-700
          active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
        "
        data-te-ripple-init
        data-te-ripple-color="light">
        <%= link_to "Cancel", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Cancel your appointment for room: #{booking.room.name}?" }  %>
      </button>
    </div>
  <% end %>


  </div>
  <div class="tab-pane fade py-3" id="requests-tab-pane" role="tabpanel" aria-labelledby="requests-tab" tabindex="0">
      <p class="text-2xl font-bold ml-12"> <%= @requests.any? ? "Pending Requests" : "No requests yet"%> </p>

 <% @requests.each do |request| %>
    <div
      class="
        block
        rounded-lg
        bg-white
        p-6
        w-96
        ml-12
        my-8
        shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)]
      ">
      <h5
        class="
          mb-4
          text-xl
          font-bold
          leading-tight
          text-neutral-800
        ">
        <%= request.room.category %>
      </h5>
      <p class="mb-1 text-base text-blue-800">
        Status: <%= request.status %>
      </p>
        <p>Room: <%= request.room.name %></p>
        <p>Date: <%= request.date %></p>
        <p>Time: <%= request.startFrom %></p>
        <p>Duration: <%= request.hours %> hours</p>

      <p class="mb-1 pb-0 text-base text-neutral-600">
        Details: <%= request.comment %>
      </p>
      <% if request.pending? %>
        <%= simple_form_for [:hospital, request] do |f| %>
        <p class="mb-2 pt-0 text-base text-neutral-800">
          <div class="flex gap-2">
          <%= f.input :status, as: :hidden, input_html: { value: 'confirmed'} %>
          <%= f.submit 'Accept', class: 'inline-block
          rounded
          bg-slate-500
          px-6
          pb-2
          mt-4
          pt-2.5
          text-xs
          font-medium
          uppercase
          leading-normal
          text-white
          shadow-[0_4px_9px_-4px_#3b71ca]
          transition
          duration-150
          ease-in-out
          hover:bg-primary-600
          hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
          focus:bg-primary-600
          focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
          focus:outline-none
          focus:ring-0
          active:bg-primary-700
          active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]' %>
          </p>
        <% end %>
        <%= simple_form_for request do |f| %>
          <%= f.input :status, as: :hidden, input_html: { value: 'rejected'} %>
          <%= f.submit 'Reject', class: ' inline-block
          rounded
          bg-red-500
          px-6
          pb-2
          mt-4
          pt-2.5
          text-xs
          font-medium
          uppercase
          leading-normal
          text-white
          shadow-[0_4px_9px_-4px_#3b71ca]
          transition
          duration-150
          ease-in-out
          hover:bg-primary-600
          hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
          focus:bg-primary-600
          focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]
          focus:outline-none
          focus:ring-0
          active:bg-primary-700
          active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]' %>
        <% end %>
      <% else %>
        <p class='booking-tag'><%= request.status %></p>
      <% end %>
      </div>
    </div>
  <% end %>

  </div>
</div>

  </div>

  <div class="flex-1 container mt-12 mr-16">

  <h1 class="text-2xl font-bold mb-8">My Calendar:</h1>
  <%= month_calendar(events: @bookings) do |date, bookings| %>
    <%= date.day %>
    <% bookings.each do |booking| %>
      <p class="font-semibold text-sm"><%= booking.room.name %></p>
    <% end %>
  <% end %>
</div>
</div>

<script>
  // Initialization for ES Users
  import {
    Ripple,
    initTE,
  } from "tw-elements";

  initTE({ Ripple });
</script>

app/views/hospital/rooms/edit.html.erb
<p>Edit <%= @room.name %></p>
<%= render 'editForm', categories: @categories, equipments: @equipments %>

app/views/hospital/rooms/index.html.erb
<div class="flex justify-between">
  <div class="my-4 px-4">
    <h2 class="text-4xl font-bold dark:text-black">Your Rooms</h2>
  </div>
  <div class="my-4 px-4">
    <%= link_to "Your Bookings", hospital_bookings_path, class: "text-slate-100 bg-blue-500 hover:text-blue-700 hover:bg-white active:bg-blue-600 font-bold py-2 px-4 mx-2" %>
    <%= link_to "List Room", new_room_path, class: "text-slate-100 bg-blue-500 hover:text-blue-700 hover:bg-white active:bg-blue-600 font-bold py-2 px-4 mx-2" %>
  </div>
</div>
<!-- room name, equipments, capacity, price -->
<div class="flex flex-col space-y-4 mx-2 py-2">
  <% @rooms.each do |room| %>
    <div class="h-32 max-w-sm w-1/2 lg:max-w-full flex px-2">
      <div class="h-48 lg:h-auto lg:w-48 flex-none bg-center bg-cover rounded-t lg:rounded-t-none lg:rounded-l overflow-hidden" >
        <%= cl_image_tag room.photos.first.key, alt: "room image", class: 'roomPic rounded-t-lg bg-cover w-full h-80 bg-center object-cover' %>
      </div>
      <div class="grow align-middle shadow bg-white rounded-b lg:rounded-b-none lg:rounded-r px-4 py-2 flex flex-col justify-between leading-normal">
        <div class="mb-8">
          <div class="text-gray-900 font-bold text-lg mb-2"><%= room.name %></div>
          <p class="text-gray-700 text-justify text-ellipsis overflow-hidden">Price: ¥<%= room.price_per_hour %> /hr</p>
          <!--
          <p class="text-gray-700 text-justify text-ellipsis overflow-hidden">Capacity: <%= room.capacity %></p>
          -->
          <p class="text-gray-700 text-justify text-ellipsis overflow-hidden">Equipments: <%= room.equipment %></p>
          <%= link_to "Edit", edit_hospital_room_path(room) %>
          <%= link_to "Delete", hospital_room_path(room), data: { turbo_method: :delete, turbo_confirm: "Delete #{room.name} ?"} %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>

app/views/pages/home.html.erb
<!-- starts here -->
<section style="background-image: url(<%= asset_path('landing.jpg') %>); background-size: cover; background-position: center;">


    <div
      class="absolute inset-0 bg-white/75 sm:bg-transparent sm:from-white/95 sm:to-white/25 ltr:sm:bg-gradient-to-r rtl:sm:bg-gradient-to-l"
    >
    </div>

    <div
      class="relative mx-auto max-w-screen-xl px-4 py-32 sm:px-6 lg:flex lg:h-screen lg:items-center lg:px-8"
    >
      <div class="max-w-xl text-center ltr:sm:text-left rtl:sm:text-right">
        <h1 class="text-3xl font-extrabold sm:text-5xl">
          Simplify surgery scheduling with

          <strong class="block font-extrabold text-blue-800">
            MedEase
          </strong>
        </h1>

        <p class="mt-4 max-w-lg sm:text-xl/relaxed text-center mx-auto font-bold">
          The hassle-free way to rent an operation room
        </p>

        <div class="mt-8 flex flex-wrap gap-4 text-center justify-center">
          <%= link_to "I'm a Doctor", rooms_path, class: "block w-full rounded bg-blue-800 px-12 py-3 text-sm font-medium text-white shadow hover:bg-blue-700 focus:outline-none focus:ring active:bg-blue-500 sm:w-auto"%>

          <%= link_to "For Hospitals", hospital_bookings_path, class: "block w-full rounded bg-white px-12 py-3 text-sm font-medium text-blue-800 shadow hover:text-blue-700 focus:outline-none focus:ring active:text-blue-500 sm:w-auto" %>
        </div>
      </div>

  </div>

</section>

app/views/rooms/index.html.erb
<div class="entire" data-controller="booking-form" data-action= "change->booking-form#filtering" data-booking-form-target="searchBox">
  <%= render "shared/banner" %>
  <div class="flex justify-content-center mx-auto">
    <div class="col-sm-8 mt-10">
      <%= form_with url: rooms_path, method: :get, class: "flex gap-10" do |form| %>
        <%= render "shared/date" %>
        <%= text_field_tag :query,
            params[:query],
            class: "",
            placeholder: "Type your address"
        %>
        <div class="row w-full flex-1 mr-1"><%= select_tag :category, options_for_select(Room::CATEGORIES, params[:category]), prompt: "Select a category" %> </div>
        <div class="row w-full flex-1"><%= select_tag :equipment, options_for_select(Room::EQUIPMENTS, params[:equipment]), prompt: "Select an equipment" %></div>
        <%= submit_tag "Search", name: "", class: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-10 rounded" %>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
    </div>
  </div>
  <div class="mx-4 mt-6">
    <div class="grid grid-cols-3 gap-6">

      <% @rooms.each do |room| %>
        <div
  class="block rounded-lg bg-white shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)]">
          <%= link_to room_path(room) do %>
            <%= cl_image_tag room.photos.first.key, alt: "room image", class: 'roomPic rounded-t-lg bg-cover w-full h-80 bg-center' %>
          <% end %>
          <div class="px-4 py-4">
          <div class="flex justify-between">
            <h2 class="text-xl pb-0 pt-0 font-bold" > <%= room.facility_name %> </h2>
            <p class="text-sm font-bold italic"><%= room.address %></p>
          </div>
          <div class="pb-0 pt-0 mb-1 text-md font-medium text-neutral-800 flex justify-between">
            <p class="font-medium text-md"><%= room.category %></p>
            <p class="text-sm font-bold"></p>
          </div>
          <div class="pb-0 pt-0 flex justify-between">
            <p>¥<%= room.price_per_hour %> /hr</p>
            <p class="text-slate-400">Capacity: <%= room.capacity %> People</p>
          </div>
            </p>
          </button>
        </div>
      </div>
    <% end %>
  </div>
</div>















      <!--
      <% @rooms.each do |room| %>
        <div
  class="block rounded-lg bg-white shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)]">
          <%= link_to room_path(room) do %>
            <%= cl_image_tag room.photos.first.key, alt: "room image", class: 'roomPic rounded-t-lg bg-cover w-full h-80 bg-center' %>
        <% end %>
        <div class="px-4 py-4">
          <div class="flex justify-between">
            <h2 class="text-xl pb-0 pt-0 font-bold" > <%= room.facility_name %> </h2>
            <p class="text-sm font-bold italic"><%= room.address %></p>
          </div>
          <div class="pb-0 pt-0 mb-1 text-md font-medium text-neutral-800 flex justify-between">
            <p class="font-medium text-md"><%= room.category %></p>
            <p class="text-sm font-bold"></p>
          </div>
          <div class="pb-0 pt-0 flex justify-between">
            <p>¥<%= room.price_per_hour %> /hr</p>
            <p class="text-slate-400">Capacity: <%= room.capacity %> People</p>
          </div>
        </p>
      </button>
    </div>
  </div>
</div>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.first_name %></h1>
<h1><%= @user.last_name %></h1>